{"name": "Тест ошибки при авторизации курьера с неверным логином", "status": "passed", "start": 1706636492252, "stop": 1706636492564, "uuid": "06771912-bedf-40bc-acf8-d892b4db58d6", "historyId": "29be3c4452055c8be93c1de55e2680de", "testCaseId": "29be3c4452055c8be93c1de55e2680de", "fullName": "tests.test_login_courier.TestLoginCourier#test_login_courier_wrong_login_error", "labels": [{"name": "story", "value": "Тесты на логин курьера"}, {"name": "parentSuite", "value": "tests"}, {"name": "suite", "value": "test_login_courier"}, {"name": "subSuite", "value": "TestLoginCourier"}, {"name": "host", "value": "Asus"}, {"name": "thread", "value": "14252-MainThread"}, {"name": "framework", "value": "pytest"}, {"name": "language", "value": "cpython3"}, {"name": "package", "value": "tests.test_login_courier"}]}