{"name": "Тест ошибки при авторизации курьера с неверным логином", "status": "passed", "start": 1706560727238, "stop": 1706560727500, "uuid": "3d290990-2c13-4843-9d92-9ed86bc3b9ca", "historyId": "29be3c4452055c8be93c1de55e2680de", "testCaseId": "29be3c4452055c8be93c1de55e2680de", "fullName": "tests.test_login_courier.TestLoginCourier#test_login_courier_wrong_login_error", "labels": [{"name": "story", "value": "Тесты на логин курьера"}, {"name": "parentSuite", "value": "tests"}, {"name": "suite", "value": "test_login_courier"}, {"name": "subSuite", "value": "TestLoginCourier"}, {"name": "host", "value": "Asus"}, {"name": "thread", "value": "1684-MainThread"}, {"name": "framework", "value": "pytest"}, {"name": "language", "value": "cpython3"}, {"name": "package", "value": "tests.test_login_courier"}]}